TemplateApp/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # path('', views.index, name='index'),
    path('home', views.home, name='home'),
    path('members', views.members, name='members'),
    path('member/<int:id>', views.member, name='member'),
    # path('hello', views.index, name='index'),
    # path('page/<str:user_name>', views.user_page, name='user_page'),
    # path('num_page/<int:number>', views.number_page, name='number_page'),
    # path('num_page/<str:user_name>/<int:number>', views.number_page, name='number_page'),
]

TemplateExam/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template_app/', include('TemplateApp.urls')),
]

TemplateApp/models.py
from django.db import models

# Create your models here.

TemplateApp/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')



class Member:
    def __init__(self, id, name, join_at, picture_path):
        self.id = id
        self.name = name
        self.join_at = join_at
        self.picture_path = picture_path

member_list = [
    Member(0, 'Taro', '1900/07/12', 'img/snake.png'),
    Member(1, 'Jiro', '1900/05/11', 'img/jiro.jpg'),
    Member(2, 'Hanako', '1900/08/24', 'img/hanako.jpg'),
    Member(3, 'Yoshiko', '1900/11/04', 'img/yoshiko.jpg'),
    ]


def members(request):
    return render(request, 'members.html', context = {
        'members' : member_list,
    })


def member(request, id):
    return render(request, 'member_detail.html', context = {
        'member' : member_list[id],
    })

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset = 'utf-8'>
        <title>{% block title %}Django大学陸上部モーム{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class ="navbar-brand" href="{% url 'app:home' %}">Home</a>
            <a class ="navbar-brand" href="{% url 'app:members' %}">Members</a>
        </nav>
        {% block content %}{% endblock %}
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title%} Home {{ block.super }}{% endblock %}
{% block content %}
<p>Django大学陸上部ホーム</p>
{% endblock %}

templates/member_detail.html
{% extends "base.html" %}
{% block title%} Member Detail {{ block.super }}{% endblock %}
{% block content %}

{% load static %}
{% load custom_tags %}
    <img src="{% static member.picture_path %}">
    <p>Name: {{ member.name }}</p>
    <p>Been at the company for: {{ member.join_at|calculate_datetime_to_now}}</p>

{% endblock %}

templates/members.html
{% extends "base.html" %}
{% block title%} Members {{ block.super }}{% endblock %}
{% block content %}

{% for member in members%}
    <p><a href="{% url 'app:member' id=member.id %}">{{member.name}} </a></p>
{% endfor%}


{% endblock %}